### ISSUE TITLE
NWB and permissive license?

### ISSUE THREAD

**Issue by bendichter** [nel-lab/FIOLA#7]
This package looks great! If there is any interest in integrating this into NWB, I'd be happy to help either reading NWB data or writing the resulting ROIs and traces into NWB.

I noticed that you have a custom license that is non-permissive to commercial entities. Would you consider changing this to open-permissive like MIT, BSD, or Apache?

**Comment by agiovann** [comment]
Closing since the license need to stay that way for the moment, thanks for noticing @bendichter
